name: openwrt_manager
description: OpenWRT Manager app for your devices.

version: 1.09.2+201092

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  path_provider: ^2.0.5
  rflutter_alert: ^2.0.4
  uuid: ^3.0.5
  http: ^0.13.4
  package_info: ^2.0.2
  feature_discovery: ^0.14.0
  provider: ^5.0.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: "assets/icon/openwrt_manager.png" 
  android: true
  ios: true

flutter:
  assets:
    - assets/
  uses-material-design: true
  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

